// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hnqhmwfzeygaktmhscfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhucWhtd2Z6ZXlnYWt0bWhzY2ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MzY4OTcsImV4cCI6MjA3MjUxMjg5N30.FkKj5IEsnITvvhS4IedkyJlj2KBP3QFw3DU9NXtl3gM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);